### ISSUE TITLE
Not working after 30m/1h with Error Connection to remote host was lost. - goodbye 

### ISSUE THREAD

**Issue by Pascal4Games** [dennis1804/homewizard-climate-hass#22]
Hello, have you already found a solution for the problem that after restarting home assistant or reloading the integration, it stops working after 30m/1h? Because I can't find anything about it (but I may have missed it).

If problem still exists, I think I have found a temporary solution with the help of automations in side of home assistant.
The automation is looking in the log and when the error message "Connection to remote host was los. -goodbye" comes he reloads the integration.

See explain below:

Automation

```
alias: Homewizard Climate Reload
description: ""
trigger:
  - platform: event
    event_type: system_log_event
    event_data:
      level: ERROR
      name: websocket
      message:
        - Connection to remote host was lost. - goodbye
condition: []
action:
  - service: shell_command.homewizard_reload
    data: {}
  - delay:
      hours: 0
      minutes: 2
      seconds: 30
      milliseconds: 0
mode: single
``` 
add inside configuration.yaml:

```
system_log:
  fire_event: true
shell_command:
   homewizard_reload: 'curl -X POST "http://[HA_IP]:8123/api/config/config_entries/entry/[config_entry]/reload" --oauth2-bearer "[Long-lived access token]"'
``` 

Replace in the shell_command:
  [HA_IP] => Home assistant local ip
  [config_entry]=> integration > homewizard climate > device > inside the url-bar you see config_entry=xxxx
  [Long-lived acces token] => under profile, scroll down and create a acces code.
